"""ITパスポート 略語・用語辞典(独自の言い回しで作成)。 (略語, 英語のフル表記, 日本語の意味)"""

TERMS = [
    ("ABC分析", "ABC Analysis", "貢献度の高い順にA・B・Cに分け、Aに力を入れる管理手法"),
    ("ACID", "Atomicity, Consistency, Isolation, Durability", "トランザクションが満たすべき4つの性質(原子性・一貫性・独立性・耐久性)"),
    ("AI", "Artificial Intelligence", "人間の知的な判断をコンピュータで実現する技術"),
    ("API", "Application Programming Interface", "プログラムの機能を、他のプログラムから呼び出すための窓口"),
    ("AR", "Augmented Reality", "拡張現実。現実の風景にデジタル情報を重ねて表示する"),
    ("B/S", "Balance Sheet", "貸借対照表。ある時点の資産・負債・純資産を表す"),
    ("BCP", "Business Continuity Plan", "事業継続計画。災害時にも重要な事業を続ける計画"),
    ("BI", "Business Intelligence", "蓄積したデータを分析・可視化し、経営判断に活かすツール"),
    ("BLE", "Bluetooth Low Energy", "省電力のBluetooth規格。IoT向き"),
    ("BPM", "Business Process Management", "業務プロセスを継続的に管理・改善する手法"),
    ("BPO", "Business Process Outsourcing", "業務の一部を外部に委託すること"),
    ("BPR", "Business Process Re-engineering", "業務プロセスを抜本的に見直して再構築すること"),
    ("BSC", "Balanced Scorecard", "財務・顧客・業務プロセス・学習と成長の4視点で評価する手法"),
    ("C/F", "Cash Flow Statement", "キャッシュフロー計算書。一定期間の現金の流れを表す"),
    ("CA", "Certificate Authority", "認証局。公開鍵の持ち主を、電子証明書で保証する機関"),
    ("CAD", "Computer Aided Design", "コンピュータを使った設計支援"),
    ("CAM", "Computer Aided Manufacturing", "コンピュータを使った製造支援"),
    ("CEO", "Chief Executive Officer", "最高経営責任者"),
    ("CFO", "Chief Financial Officer", "最高財務責任者"),
    ("CIM", "Computer Integrated Manufacturing", "設計から製造・販売までの情報を統合する生産方式"),
    ("CIO", "Chief Information Officer", "最高情報責任者"),
    ("CISO", "Chief Information Security Officer", "最高情報セキュリティ責任者"),
    ("COO", "Chief Operating Officer", "最高執行責任者"),
    ("CPU", "Central Processing Unit", "中央処理装置。コンピュータの頭脳"),
    ("CRM", "Customer Relationship Management", "顧客関係管理。顧客情報や対応履歴で満足度を高める"),
    ("CSF", "Critical Success Factor", "重要成功要因。ゴール達成に欠かせない要因"),
    ("CSR", "Corporate Social Responsibility", "企業の社会的責任"),
    ("CSV", "Creating Shared Value", "社会課題の解決と、自社の利益を両立させる経営(共有価値の創造)"),
    ("CTO", "Chief Technology Officer", "最高技術責任者"),
    ("DBMS", "Database Management System", "データベース管理システム"),
    ("DDoS", "Distributed Denial of Service", "多数の機器から同時に大量のアクセスを送り、サービスを止める攻撃"),
    ("DFD", "Data Flow Diagram", "データの流れを表す図"),
    ("DHCP", "Dynamic Host Configuration Protocol", "IPアドレスなどを、機器に自動で割り当てる仕組み"),
    ("DMZ", "DeMilitarized Zone", "外部と内部のネットワークの間に設ける緩衝区画"),
    ("DNS", "Domain Name System", "ドメイン名とIPアドレスを対応づける仕組み"),
    ("DoS", "Denial of Service", "大量のアクセスなどで、サービスを使えなくする攻撃"),
    ("DWH", "Data Warehouse", "分析用に整理された、巨大なデータの保管庫"),
    ("DX", "Digital Transformation", "ITでビジネスモデルや組織を変革すること"),
    ("EA", "Enterprise Architecture", "業務とシステムの現状と理想を整理し、全体最適を目指す設計手法"),
    ("EC", "Electronic Commerce", "電子商取引"),
    ("EDI", "Electronic Data Interchange", "企業間で、取引データを標準化した形式で電子的にやり取りする"),
    ("EMS", "Electronics Manufacturing Service", "電子機器の製造を専門に受託するサービス"),
    ("ERP", "Enterprise Resource Planning", "ヒト・モノ・カネ・情報を一元管理する仕組み"),
    ("ESG", "Environment, Social, Governance", "環境・社会・企業統治。投資家が企業を評価する観点"),
    ("E-R図", "Entity-Relationship Diagram", "データの構造と関係を表す図"),
    ("EV", "Earned Value", "出来高。EVMで、実際に完了した作業の価値"),
    ("EVM", "Earned Value Management", "計画と実績を比べて、進捗とコストを管理する手法"),
    ("FIFO", "First In First Out", "先入れ先出し。キューの特徴"),
    ("FP", "Function Point", "利用者から見える機能の数や難易度で、システムの規模を測る方法"),
    ("FTP", "File Transfer Protocol", "ファイルを転送するためのプロトコル"),
    ("GPS", "Global Positioning System", "全地球測位システム"),
    ("GUI", "Graphical User Interface", "マウスなどで操作する、グラフィカルな画面"),
    ("HTTP", "HyperText Transfer Protocol", "Webの通信に使うプロトコル。HTTPSは暗号化版"),
    ("IaaS", "Infrastructure as a Service", "サーバなどのインフラを、サービスとして提供する形態"),
    ("IDE", "Integrated Development Environment", "統合開発環境。開発に必要な機能をまとめたソフト"),
    ("IDS", "Intrusion Detection System", "不正侵入検知システム。検知して知らせる"),
    ("IMAP4", "Internet Message Access Protocol 4", "サーバ上のメールを管理しながら受信するプロトコル"),
    ("IoT", "Internet of Things", "モノがインターネットにつながる仕組み"),
    ("IPS", "Intrusion Prevention System", "不正侵入防御システム。検知して遮断する"),
    ("ISMS", "Information Security Management System", "情報セキュリティマネジメントシステム"),
    ("ITIL", "Information Technology Infrastructure Library", "ITサービス運用のベストプラクティス集"),
    ("JIT", "Just In Time", "必要なものを、必要なときに、必要なだけ供給する生産方式"),
    ("KGI", "Key Goal Indicator", "重要目標達成指標。最終ゴールの指標"),
    ("KPI", "Key Performance Indicator", "重要業績評価指標。途中経過の指標"),
    ("LAN", "Local Area Network", "構内のネットワーク"),
    ("LIFO", "Last In First Out", "後入れ先出し。スタックの特徴"),
    ("LLM", "Large Language Models", "大規模言語モデル"),
    ("LPWA", "Low Power Wide Area", "低消費電力で、広範囲に通信できる無線通信"),
    ("M&A", "Mergers and Acquisitions", "合併・買収"),
    ("MaaS", "Mobility as a Service", "さまざまな交通手段を、1つのサービスとして統合する"),
    ("MAC", "Media Access Control address", "機器固有のアドレス(MACアドレス)"),
    ("MECE", "Mutually Exclusive, Collectively Exhaustive", "漏れなく、ダブりなく分類する考え方"),
    ("MIPS", "Million Instructions Per Second", "1秒間に実行できる命令数(100万単位)"),
    ("MOT", "Management of Technology", "技術経営"),
    ("MRP", "Material Requirements Planning", "資材所要量計画"),
    ("MTBF", "Mean Time Between Failures", "平均故障間隔(動いていた時間の平均)"),
    ("MTTR", "Mean Time To Repair", "平均修理時間"),
    ("NAT", "Network Address Translation", "プライベートIPとグローバルIPを変換する技術"),
    ("NDA", "Non-Disclosure Agreement", "秘密保持契約"),
    ("O2O", "Online to Offline", "ネットから実店舗への来店を促す施策"),
    ("OCR", "Optical Character Reader", "光学式文字読み取り装置"),
    ("OEM", "Original Equipment Manufacturing", "他社ブランドの製品を製造すること"),
    ("OJT", "On the Job Training", "仕事をしながら学ぶ教育"),
    ("OMR", "Optical Mark Reader", "光学式マーク読み取り装置(マークシートなど)"),
    ("OS", "Operating System", "コンピュータを動かす基本のソフト"),
    ("OSS", "Open Source Software", "ソースコードが公開され、利用・改変・再配布できるソフト"),
    ("P/L", "Profit and Loss Statement", "損益計算書。一定期間の収益と費用、利益"),
    ("PaaS", "Platform as a Service", "アプリを動かす基盤(OS・ミドルウェアまで)を提供する形態"),
    ("PDCA", "Plan, Do, Check, Act", "計画・実行・評価・改善のサイクル"),
    ("PERT", "Program Evaluation and Review Technique", "作業の順序と日数から日程を管理する手法"),
    ("PKI", "Public Key Infrastructure", "公開鍵暗号を使った、認証や署名の基盤"),
    ("PMBOK", "Project Management Body of Knowledge", "プロジェクトマネジメントの知識体系"),
    ("POS", "Point Of Sales", "販売時点情報管理"),
    ("PPM", "Product Portfolio Management", "複数事業への資源配分を判断する手法"),
    ("PoC", "Proof of Concept", "概念実証。技術的に実現できるかの検証"),
    ("PoV", "Proof of Value", "価値実証。事業として価値があるかの検証"),
    ("POP3", "Post Office Protocol 3", "メールを受信してダウンロードするプロトコル"),
    ("PV", "Planned Value", "計画値。EVMで、計画した作業の価値"),
    ("RAID", "Redundant Arrays of Inexpensive Disks", "複数のディスクを組み合わせて、速度や信頼性を高める技術"),
    ("RAM", "Random Access Memory", "主記憶に使われる、読み書きできるメモリ"),
    ("RASIS", "Reliability, Availability, Serviceability, Integrity, Security", "信頼性・可用性・保守性・完全性・安全性"),
    ("RFI", "Request For Information", "情報提供依頼書"),
    ("RFID", "Radio Frequency Identification", "無線で情報を読み書きできるICタグの技術"),
    ("RFP", "Request For Proposal", "提案依頼書"),
    ("ROI", "Return On Investment", "投資対効果"),
    ("ROM", "Read Only Memory", "読み出し専用のメモリ"),
    ("RPA", "Robotic Process Automation", "定型的な事務作業を、ソフトウェアのロボットで自動化する"),
    ("SaaS", "Software as a Service", "アプリケーションを、サービスとして提供する形態"),
    ("SCM", "Supply Chain Management", "供給の連鎖全体を最適化する管理"),
    ("SDGs", "Sustainable Development Goals", "持続可能な開発目標。国連が定めた世界共通の目標"),
    ("SEO", "Search Engine Optimization", "検索結果で上位に表示されるようにする最適化"),
    ("SFA", "Sales Force Automation", "営業活動を支援・管理するシステム"),
    ("SI", "System Integration", "情報システムの設計・開発・導入・運用を一括して請け負う事業"),
    ("SLA", "Service Level Agreement", "サービスレベルの合意書"),
    ("SLM", "Service Level Management", "サービスレベル管理"),
    ("SMTP", "Simple Mail Transfer Protocol", "メールの送信・中継のプロトコル"),
    ("SNS", "Social Networking Service", "人と人のつながりを提供するサービス"),
    ("SQL", "Structured Query Language", "データベースを操作するための言語"),
    ("SSL/TLS", "Secure Sockets Layer / Transport Layer Security", "通信を暗号化するプロトコル"),
    ("STP", "Segmentation, Targeting, Positioning", "市場細分化・標的市場の選定・位置づけ"),
    ("SWOT", "Strength, Weakness, Opportunity, Threat", "強み・弱み・機会・脅威を整理する分析"),
    ("TCO", "Total Cost of Ownership", "総所有コスト。導入から運用・保守までの総額"),
    ("TCP/IP", "Transmission Control Protocol / Internet Protocol", "インターネットで使う通信プロトコルの集まり"),
    ("UPS", "Uninterruptible Power Supply", "無停電電源装置"),
    ("UX", "User Experience", "利用者が使って感じる体験全体"),
    ("VPN", "Virtual Private Network", "インターネット上に作る、暗号化された専用の通信路"),
    ("VR", "Virtual Reality", "仮想現実。完全に仮想の空間に入り込む"),
    ("VRIO", "Value, Rarity, Imitability, Organization", "経営資源を、価値・希少性・模倣困難性・組織で評価する分析"),
    ("WAF", "Web Application Firewall", "Webアプリケーションを守るファイアウォール"),
    ("WAN", "Wide Area Network", "広域のネットワーク"),
    ("WBS", "Work Breakdown Structure", "作業を階層的に分解した構成図"),
    ("XSS", "Cross Site Scripting", "Webサイトの脆弱性を突いて、不正なスクリプトを実行させる攻撃"),
]
